"""Cluster-bootstrap CIs + paired tests for the Alibaba sizing panel.

Reads unified_alibaba.csv (produced by unified_eval_alibaba.py) and emits
alibaba_panel_stats.json: per-method share-at-target and SLA net-revenue
ratios with 95% VM-clustered bootstrap CIs, plus the paired per-VM sign
test of lognorm_ctop vs each baseline on AWS net revenue. Same estimator
as bootstrap_cis.py / sla_paired.py so the Alibaba column is
apples-to-apples with the Bitbrains panel.
"""
import json, os, numpy as np, pandas as pd
from scipy.stats import binomtest

B = 2000
RNG = np.random.default_rng(42)
HERE = os.path.dirname(os.path.abspath(__file__))
# ml_gbm excluded: needs >=8 training days, n/a on the 8-day Alibaba trace
METHODS = ["lognorm_ctop", "empirical_p998", "gauss_meanksd",
           "rolling_max", "ewmq_p998"]

def credit(a, prov):
    if a >= 0.9999: return 0.0
    if a >= 0.99:   return 0.10
    if a >= 0.95:   return 0.25
    return 1.00 if prov != "GCP" else 0.50

def boot_ci(per_vm_vals, agg=np.mean):
    arr = np.asarray(per_vm_vals, float); arr = arr[np.isfinite(arr)]
    n = len(arr); bs = np.empty(B)
    for b in range(B):
        bs[b] = agg(arr[RNG.integers(0, n, n)])
    return {"point": float(agg(arr)),
            "ci_low": float(np.percentile(bs, 2.5)),
            "ci_hi": float(np.percentile(bs, 97.5)), "n_vms": int(n)}

df = pd.read_csv(os.path.join(HERE, "unified_alibaba.csv"))

def per_vm_avail(col):
    def wm(g):
        m = g[col].notna()
        if m.sum() == 0: return np.nan
        return (g.loc[m, col] * g.loc[m, "n_test"]).sum() / g.loc[m, "n_test"].sum()
    return df.groupby("vm").apply(wm, include_groups=False)

out = {"n_vms": int(df["vm"].nunique()), "n_bins": int(len(df)),
       "median_n_test": int(df["n_test"].median())}

# share-at-target (per-VM share of bins with coverage >= 0.998)
share = {}
for m in METHODS:
    col = f"cov_{m}"
    d = df[df[col].notna()].copy()
    d["hit"] = d[col] >= 0.998
    per_vm = d.groupby("vm")["hit"].mean()
    share[m] = boot_ci(per_vm.values)
    share[m]["median_ceiling"] = float(df[f"ctop_{m}"].median())
out["share_at_target"] = share

# SLA net revenue per provider
sla = {}
avail = {m: per_vm_avail(f"cov_{m}") for m in METHODS}
for prov in ["AWS", "GCP", "Azure"]:
    pm = {}
    for m in METHODS:
        net = avail[m].dropna().apply(lambda a: 1 - credit(a, prov))
        pm[m] = boot_ci(net.values)
    sla[prov] = pm
out["sla_net_revenue"] = sla

# paired LN vs each baseline, AWS
paired = {}
J = pd.DataFrame(avail).dropna()
for m in METHODS:
    if m == "lognorm_ctop": continue
    ln = J["lognorm_ctop"].apply(lambda a: 1 - credit(a, "AWS"))
    bs = J[m].apply(lambda a: 1 - credit(a, "AWS"))
    win = int((ln > bs).sum()); loss = int((ln < bs).sum()); tie = int((ln == bs).sum())
    p = binomtest(win, win + loss).pvalue if win + loss else 1.0
    paired[m] = {"lognorm_cheaper_wins": win, "losses": loss, "ties": tie,
                 "sign_test_p": float(p), "n": int(len(J))}
out["paired_vs_lognorm_AWS"] = paired

with open(os.path.join(HERE, "alibaba_panel_stats.json"), "w") as f:
    json.dump(out, f, indent=2)

# ---- emit LaTeX macros ----
ABBR = {"lognorm_ctop": "LN", "empirical_p998": "EP", "gauss_meanksd": "GA",
        "rolling_max": "RM", "ewmq_p998": "EWMQ"}
def pct(x): return f"{100*x:.2f}"
lines = ["% Auto-generated by scoping/alibaba_panel_stats.py. Do not edit.",
         f"\\newcommand{{\\AliPanelNVms}}{{{out['n_vms']}}}",
         f"\\newcommand{{\\AliPanelNBins}}{{{out['n_bins']:,}}}".replace(",", "\\,"),
         f"\\newcommand{{\\AliMedNTest}}{{{out['median_n_test']}}}"]
for m, ab in ABBR.items():
    s = out["share_at_target"][m]
    lines += [f"\\newcommand{{\\Ali{ab}Share}}{{{pct(s['point'])}}}",
              f"\\newcommand{{\\Ali{ab}ShareCiLo}}{{{pct(s['ci_low'])}}}",
              f"\\newcommand{{\\Ali{ab}ShareCiHi}}{{{pct(s['ci_hi'])}}}",
              f"\\newcommand{{\\Ali{ab}Ceiling}}{{{s['median_ceiling']:.1f}}}"]
for prov in ["AWS", "GCP", "Azure"]:
    for m, ab in ABBR.items():
        s = out["sla_net_revenue"][prov][m]
        lines += [f"\\newcommand{{\\SlaAli{ab}{prov}Net}}{{{pct(s['point'])}}}",
                  f"\\newcommand{{\\SlaAli{ab}{prov}NetCiLo}}{{{pct(s['ci_low'])}}}",
                  f"\\newcommand{{\\SlaAli{ab}{prov}NetCiHi}}{{{pct(s['ci_hi'])}}}"]
pr = out["paired_vs_lognorm_AWS"]
lines += [f"\\newcommand{{\\AliPairedRMwins}}{{{pr['rolling_max']['lognorm_cheaper_wins']}}}",
          f"\\newcommand{{\\AliPairedRMloss}}{{{pr['rolling_max']['losses']}}}",
          f"\\newcommand{{\\AliPairedEPwins}}{{{pr['empirical_p998']['lognorm_cheaper_wins']}}}",
          f"\\newcommand{{\\AliPairedEPloss}}{{{pr['empirical_p998']['losses']}}}"]
with open(os.path.join(HERE, "..", "paper", "paper_macros_alibaba.tex"), "w") as f:
    f.write("\n".join(lines) + "\n")
print(json.dumps(out, indent=2))
print("wrote paper/paper_macros_alibaba.tex")
