"""Regenerate all paper macros from the unified panel + bootstrap CIs.

Overwrites paper_macros.tex to a clean single source of truth."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
PM = os.path.join(HERE, "..", "paper", "paper_macros.tex")

# unified panel summaries
un_fs = json.load(open(os.path.join(HERE, "unified_fastStorage_summary.json")))
un_rn = json.load(open(os.path.join(HERE, "unified_rnd_summary.json")))
# bootstrap
b = json.load(open(os.path.join(HERE, "bootstrap_cis.json")))

# preserved from prior generators (Sections 5, 6, 7 non-sizing, 8):
existing = open(PM).read().splitlines() if os.path.exists(PM) else []
# Keep the pre-Claim-3 macros; regenerate Claim 3 (unified) and Claim 4 (SLA on unified),
# and add CI macros.

# Reset file, then re-derive from scratch.
lines = ["% Auto-generated by scoping/build_paper_macros.py + build_ci_macros.py."]
lines += ["% --- Dataset sizes and Claim 1 winner shares ---"]
# From bitbrains and rnd fit summaries
fs = json.load(open(os.path.join(HERE, "bitbrains_summary.json")))
rn = json.load(open(os.path.join(HERE, "rnd_summary.json")))
def fmt_int(n): return f"{n:,}".replace(",", "\\,")
lines += [
    f"\\newcommand{{\\RndVms}}{{~500}}",
    f"\\newcommand{{\\NBinsFs}}{{{fmt_int(fs['n_bins'])}}}",
    f"\\newcommand{{\\NBinsRnd}}{{{fmt_int(rn['n_bins'])}}}",
    f"\\newcommand{{\\NBinsAll}}{{{fmt_int(fs['n_bins']+rn['n_bins'])}}}",
    f"\\newcommand{{\\NVmsAll}}{{{fs['n_vms_used']+rn['n_vms_used']}}}",
    f"\\newcommand{{\\NVmsFs}}{{{fs['n_vms_used']}}}",
    f"\\newcommand{{\\NVmsRnd}}{{{rn['n_vms_used']}}}",
    f"\\newcommand{{\\FsLogNorm}}{{{100*fs['best_aic_share']['lognorm']:.2f}}}",
    f"\\newcommand{{\\FsWeibull}}{{{100*fs['best_aic_share']['weibull_min']:.2f}}}",
    f"\\newcommand{{\\FsGamma}}{{{100*fs['best_aic_share']['gamma']:.2f}}}",
    f"\\newcommand{{\\FsNormal}}{{{100*fs['best_aic_share']['norm']:.2f}}}",
    f"\\newcommand{{\\RndLogNorm}}{{{100*rn['best_aic_share']['lognorm']:.2f}}}",
    f"\\newcommand{{\\RndWeibull}}{{{100*rn['best_aic_share']['weibull_min']:.2f}}}",
    f"\\newcommand{{\\RndGamma}}{{{100*rn['best_aic_share']['gamma']:.2f}}}",
    f"\\newcommand{{\\RndNormal}}{{{100*rn['best_aic_share']['norm']:.2f}}}",
]
# Combined and pairwise from stored earlier; recompute here to be sure.
tot = fs['n_bins'] + rn['n_bins']
all_share = {f: (fs['best_aic_share'][f]*fs['n_bins'] + rn['best_aic_share'][f]*rn['n_bins'])/tot
             for f in ["lognorm","weibull_min","gamma","norm"]}
lines += [
    f"\\newcommand{{\\LogNormShareAll}}{{{100*all_share['lognorm']:.2f}}}",
    f"\\newcommand{{\\WeibullShareAll}}{{{100*all_share['weibull_min']:.2f}}}",
    f"\\newcommand{{\\GammaShareAll}}{{{100*all_share['gamma']:.2f}}}",
    f"\\newcommand{{\\NormalShareAll}}{{{100*all_share['norm']:.2f}}}",
]

# --- Claim 1 CI ---
lines += ["", "% --- Claim 1 bootstrap CIs ---"]
c1 = b["claim1_winner_share"]
def ci(v): return v["ci_low"], v["ci_hi"]
lo, hi = ci(c1["combined_lognorm"])
lines += [
    f"\\newcommand{{\\LogNormShareAllCiLo}}{{{100*lo:.2f}}}",
    f"\\newcommand{{\\LogNormShareAllCiHi}}{{{100*hi:.2f}}}",
]

# --- Pairwise Claim 1 (kept from earlier build_paper_macros.py logic on combined) ---
import pandas as pd, numpy as np
fs_df = pd.read_csv(os.path.join(HERE, "bitbrains_fit_results.csv"))
rn_df = pd.read_csv(os.path.join(HERE, "rnd_fit_results.csv"))
comb = pd.concat([fs_df.assign(_ds='fs'), rn_df.assign(_ds='rn')], ignore_index=True)
for fam, tag in [("norm","Norm"), ("gamma","Gamma"), ("weibull_min","Weibull")]:
    d = (comb["aic_lognorm"] - comb[f"aic_{fam}"]).replace([np.inf,-np.inf], np.nan).dropna()
    lines += [
        f"\\newcommand{{\\FsAicDelta{tag}}}{{{float(d.median()):.1f}}}",
        f"\\newcommand{{\\FsShareVs{tag}}}{{{100*float((d < 0).mean()):.2f}}}",
        f"\\newcommand{{\\FsShareStrongVs{tag}}}{{{100*float((d <= -2).mean()):.2f}}}",
    ]

# --- Section 5 AD/CvM medians (from earlier ad_cvm_summary.json) ---
adcvm = json.load(open(os.path.join(HERE, "ad_cvm_summary.json")))
lines += ["", "% --- Section 5 AD/CvM medians ---"]
for label, tag in [("fastStorage","Fs"),("rnd","Rn")]:
    a = adcvm[label]
    for stat, stag in [("ks","KS"),("cvm","Cvm"),("ad","Ad")]:
        med = a[f"{stat}_median"]
        lines += [
            f"\\newcommand{{\\{tag}{stag}MedLN}}{{{med['lognorm']:.2f}}}",
            f"\\newcommand{{\\{tag}{stag}MedNo}}{{{med['norm']:.2f}}}",
            f"\\newcommand{{\\{tag}{stag}MedGa}}{{{med['gamma']:.2f}}}",
            f"\\newcommand{{\\{tag}{stag}MedWe}}{{{med['weibull_min']:.2f}}}",
            f"\\newcommand{{\\{tag}{stag}ShareLN}}{{{100*a[f'{stat}_share_lognorm_best']:.1f}}}",
        ]

# --- Claim 2 CIs ---
lines += ["", "% --- Claim 2: scaling mechanism CIs ---"]
c2 = b["claim2_scaling_mechanism"]
for label, tag in [("fastStorage","Fs"),("rnd","Rn")]:
    sp = c2[f"{label}_spearman"]; rt = c2[f"{label}_median_ratio"]
    lines += [
        f"\\newcommand{{\\Scal{tag}Spearman}}{{{sp['point']:.2f}}}",
        f"\\newcommand{{\\Scal{tag}SpearmanCiLo}}{{{sp['ci_low']:.2f}}}",
        f"\\newcommand{{\\Scal{tag}SpearmanCiHi}}{{{sp['ci_hi']:.2f}}}",
        f"\\newcommand{{\\Scal{tag}Ratio}}{{{rt['point']:.1f}}}",
        f"\\newcommand{{\\Scal{tag}RatioCiLo}}{{{rt['ci_low']:.1f}}}",
        f"\\newcommand{{\\Scal{tag}RatioCiHi}}{{{rt['ci_hi']:.1f}}}",
        f"\\newcommand{{\\Scal{tag}CohortN}}{{{c2[f'{label}_cohort_n']}}}",
    ]

# --- Claim 3: unified panel share-at-target and ceilings ---
lines += ["", "% --- Section 7 unified panel: share-at-target, ceiling, rel cost, and CIs ---"]
c3 = b["claim3_share_at_target"]
for label, tag, panel in [("fastStorage","Fs",un_fs), ("rnd","Rn",un_rn)]:
    lines += [
        f"\\newcommand{{\\Panel{tag}NVms}}{{{panel['n_vms']}}}",
        f"\\newcommand{{\\Panel{tag}NBins}}{{{fmt_int(panel['n_bins'])}}}",
    ]
    for method, mtag in [("lognorm_ctop","LN"),("empirical_p998","EP"),
                         ("gauss_meanksd","GA"),("rolling_max","RM"),
                         ("ml_gbm_p998","MLGB"),("ewmq_p998","EWMQ")]:
        m = panel[method]
        share = c3[label].get(method) if c3[label] else None
        lines += [
            f"\\newcommand{{\\U{tag}{mtag}MeanCov}}{{{100*m['mean_coverage']:.2f}}}",
            f"\\newcommand{{\\U{tag}{mtag}Share}}{{{100*m['share_at_target']:.2f}}}",
            f"\\newcommand{{\\U{tag}{mtag}Ceiling}}{{{m['median_ceiling_pct']:.2f}}}",
            f"\\newcommand{{\\U{tag}{mtag}RelCost}}{{{100*m['median_rel_cost']:.1f}}}",
        ]
        if share is not None:
            lines += [
                f"\\newcommand{{\\U{tag}{mtag}ShareCiLo}}{{{100*share['ci_low']:.2f}}}",
                f"\\newcommand{{\\U{tag}{mtag}ShareCiHi}}{{{100*share['ci_hi']:.2f}}}",
            ]

# --- Claim 4: SLA net revenue with CIs (all 6 methods, 3 providers) ---
lines += ["", "% --- Section 8 SLA net revenue, with CIs, all six methods ---"]
c4 = b["claim4_sla_net_revenue"]
for label, tag in [("fastStorage","Fs"),("rnd","Rn")]:
    if not c4[label]: continue
    for prov in ["AWS","GCP","Azure"]:
        for method, mtag in [("lognorm_ctop","LN"),("empirical_p998","EP"),
                             ("gauss_meanksd","GA"),("rolling_max","RM"),
                             ("ml_gbm_p998","MLGB"),("ewmq_p998","EWMQ")]:
            v = c4[label][prov].get(method) if c4[label] and c4[label].get(prov) else None
            if v is None: continue
            lines += [
                f"\\newcommand{{\\Sla{tag}{mtag}{prov}Net}}{{{100*v['point']:.2f}}}",
                f"\\newcommand{{\\Sla{tag}{mtag}{prov}NetCiLo}}{{{100*v['ci_low']:.2f}}}",
                f"\\newcommand{{\\Sla{tag}{mtag}{prov}NetCiHi}}{{{100*v['ci_hi']:.2f}}}",
            ]

# Keep the older Scaling-fit macros for the intro/Section 6 legacy references
sc = json.load(open(os.path.join(HERE, "scaling_summary.json")))
lines += ["", "% --- Section 6 legacy scaling summary ---"]
for label, tag in [("fastStorage","Fs"),("rnd","Rn")]:
    s = sc[label]
    lines += [
        f"\\newcommand{{\\Scal{tag}NVms}}{{{s['n_vms']}}}",
        f"\\newcommand{{\\Scal{tag}MuMedR}}{{{s['mu_r2']['median']:.2f}}}",
        f"\\newcommand{{\\Scal{tag}MuShareHalf}}{{{100*s['mu_r2']['share_ge_0.5']:.1f}}}",
        f"\\newcommand{{\\Scal{tag}SigMedR}}{{{s['sigma_r2']['median']:.2f}}}",
        f"\\newcommand{{\\Scal{tag}SigShareHalf}}{{{100*s['sigma_r2']['share_ge_0.5']:.1f}}}",
        f"\\newcommand{{\\Scal{tag}AlphaMed}}{{{s['alpha_median']:.4f}}}",
        f"\\newcommand{{\\Scal{tag}GammaMed}}{{{s['gamma_median']:.3f}}}",
    ]

with open(PM, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print(f"wrote {len(lines)} lines to {PM}")
