"""Alibaba goodness-of-fit macros: pairwise AIC (from alibaba_fit_results.csv)
and AD/CvM/KS medians (from ad_cvm_alibaba_summary.json, if present).
Emits paper/paper_macros_aligof.tex.
"""
import json, os
import numpy as np, pandas as pd
HERE = os.path.dirname(os.path.abspath(__file__))
def L(n, v): return f"\\newcommand{{\\{n}}}{{{v}}}"
lines = ["% Auto-generated by scoping/build_alibaba_gof_macros.py. Do not edit."]

# --- pairwise AIC ---
df = pd.read_csv(os.path.join(HERE, "alibaba_fit_results.csv"))
for c, ab in [("norm", "Norm"), ("gamma", "Gamma"), ("weibull_min", "Weibull")]:
    d = (df["aic_lognorm"] - df[f"aic_{c}"]).replace([np.inf, -np.inf], np.nan).dropna()
    lines += [L(f"AliAicDelta{ab}", f"{d.median():.1f}"),
              L(f"AliShareVs{ab}", f"{100*(d<0).mean():.2f}"),
              L(f"AliShareStrongVs{ab}", f"{100*(d<=-2).mean():.2f}")]

# --- AD/CvM/KS medians (if the stream finished) ---
p = os.path.join(HERE, "ad_cvm_alibaba_summary.json")
if os.path.exists(p):
    a = json.load(open(p))
    fam = {"lognorm": "LN", "gamma": "Ga", "norm": "No", "weibull_min": "We"}
    stat = {"ks": "KS", "cvm": "Cvm", "ad": "Ad"}
    for sn, sab in stat.items():
        for f, fab in fam.items():
            lines.append(L(f"Ali{sab}Med{fab}", f"{a[f'{sn}_median'][f]:.2f}"))
    lines.append(L("AliCvmShareLN", f"{100*a['cvm_share_lognorm_best']:.1f}"))
    lines.append(L("AliAdCvmNBins", f"{a['n_bins']:,}".replace(',', '\\,')))

with open(os.path.join(HERE, "..", "paper", "paper_macros_aligof.tex"), "w") as f:
    f.write("\n".join(lines) + "\n")
print("\n".join(lines))
