"""Macro-ize the previously-hardcoded Section 5/6/8 mechanism numbers so a
rebuild regenerates them (reviewer B5). Reads the committed summary
artifacts and diag_proxy.csv; emits paper/paper_macros_mech.tex.

Also computes the DE-CIRCULARIZED sigma-direction shares (reviewer B3):
the share of VMs with gamma_hat < 0 (sigma rises with lambda under Form A)
on the FULL proxy panel and on a cohort selected by PROXY quality
(rho_cpu_net, the independent variable), not by sigma-fit R^2 (dependent).
"""
import json, os
import numpy as np, pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
def L(name, val): return f"\\newcommand{{\\{name}}}{{{val}}}"
lines = ["% Auto-generated by scoping/build_mech_macros.py. Do not edit."]

# ---- Sigma-direction, de-circularized (diag_proxy.csv) ----
d = pd.read_csv(os.path.join(HERE, "diag_proxy.csv"))
for t, pre in [("fastStorage", "Fs"), ("rnd", "Rn")]:
    s = d[d.trace == t]
    med = s.rho_cpu_net.median()
    full = 100 * (s.gamma < 0).mean()
    hi = s[s.rho_cpu_net >= med]
    hishare = 100 * (hi.gamma < 0).mean()
    lines += [L(f"SigDir{pre}Full", f"{full:.0f}"),
              L(f"SigDir{pre}FullN", f"{len(s)}"),
              L(f"SigDir{pre}Prox", f"{hishare:.0f}"),
              L(f"SigDir{pre}ProxN", f"{len(hi)}")]

# ---- Form C (formC_summary.json) ----
fc = json.load(open(os.path.join(HERE, "formC_summary.json")))
for t, pre in [("fastStorage", "Fs"), ("rnd", "Rn")]:
    o = fc[t]
    lines += [L(f"FormC{pre}RB", f"{o['r2_medians']['B']:.2f}"),
              L(f"FormC{pre}RP", f"{o['r2_medians']['P']:.2f}"),
              L(f"FormC{pre}RC", f"{o['r2_medians']['C']:.2f}"),
              L(f"FormC{pre}AiccB", f"{100*o['best_aicc_share']['B']:.0f}"),
              L(f"FormC{pre}AiccP", f"{100*o['best_aicc_share']['P']:.0f}"),
              L(f"FormC{pre}Cpin", f"{o['c_median_pinned']:.3f}"),
              L(f"FormC{pre}SpPart", f"{o['spearman_partial_ctrl_lam']:.2f}")]

# ---- Composite proxy (composite_proxy_summary.json) ----
cp = json.load(open(os.path.join(HERE, "composite_proxy_summary.json")))
for t, pre in [("fastStorage", "Fs"), ("rnd", "Rn")]:
    o = cp[t]
    lines += [L(f"Prox{pre}Net", f"{o['median_rho_net']:.2f}"),
              L(f"Prox{pre}Comp", f"{o['median_rho_composite_all']:.2f}")]

# ---- Dispersion index (alibaba_fano_summary.json) ----
fa = json.load(open(os.path.join(HERE, "alibaba_fano_summary.json")))
lines += [L("DispFivemin", f"{fa['5min']['median_disp_high_load']:.1f}"),
          L("DispOnehr", f"{fa['1hour']['median_disp_high_load']:.1f}"),
          L("DispNhi", f"{fa['5min']['n_machines_high_load']}")]

# ---- Paired sign-test counts (sla_paired_summary.json) ----
sp = json.load(open(os.path.join(HERE, "sla_paired_summary.json")))
def paired(trace, prov, base, pre):
    o = sp[trace][prov][base]
    lines.append(L(f"{pre}Win", f"{o['wins_lognorm_cheaper']}"))
    lines.append(L(f"{pre}Loss", f"{o['losses']}"))
    lines.append(L(f"{pre}Tie", f"{o['ties']}"))
for base, pre in [("rolling_max","PairFsRM"),("empirical_p998","PairFsEP"),
                  ("gauss_meanksd","PairFsGA"),("ml_gbm_p998","PairFsML"),
                  ("ewmq_p998","PairFsEW")]:
    paired("fastStorage","AWS",base,pre)
paired("rnd","AWS","rolling_max","PairRnRM")

with open(os.path.join(HERE, "..", "paper", "paper_macros_mech.tex"), "w") as f:
    f.write("\n".join(lines) + "\n")
print("\n".join(lines))
print("\nwrote paper/paper_macros_mech.tex")
