"""Rebuild paper_macros.tex from a SINGLE co-computed source.

Fix: prior build mixed unified-panel pooled point estimates with
bootstrap-derived VM-weighted CIs, producing point-outside-CI cases (GBM).
This version uses the bootstrap `point` field (VM-weighted) for every
value that carries a CI in the paper, so point and interval always come
from the same aggregation.
"""
import json, os, sys
import numpy as np, pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
PM = os.path.join(HERE, "..", "paper", "paper_macros.tex")

boot = json.load(open(os.path.join(HERE, "bootstrap_cis.json")))
un_fs = json.load(open(os.path.join(HERE, "unified_fastStorage_summary.json")))
un_rn = json.load(open(os.path.join(HERE, "unified_rnd_summary.json")))
fs = json.load(open(os.path.join(HERE, "bitbrains_summary.json")))
rn = json.load(open(os.path.join(HERE, "rnd_summary.json")))
adcvm = json.load(open(os.path.join(HERE, "ad_cvm_summary.json")))
sc = json.load(open(os.path.join(HERE, "scaling_summary.json")))

def fmt_int(n): return f"{n:,}".replace(",", "\\,")

lines = ["% Auto-generated by scoping/build_ci_macros_v2.py. Do not edit."]

# --- Section 5: dataset sizes and Claim 1 (winner share) ---
lines += ["", "% --- Dataset sizes ---",
    f"\\newcommand{{\\RndVms}}{{~500}}",
    f"\\newcommand{{\\NBinsFs}}{{{fmt_int(fs['n_bins'])}}}",
    f"\\newcommand{{\\NBinsRnd}}{{{fmt_int(rn['n_bins'])}}}",
    f"\\newcommand{{\\NBinsAll}}{{{fmt_int(fs['n_bins']+rn['n_bins'])}}}",
    f"\\newcommand{{\\NVmsAll}}{{{fs['n_vms_used']+rn['n_vms_used']}}}",
    f"\\newcommand{{\\NVmsFs}}{{{fs['n_vms_used']}}}",
    f"\\newcommand{{\\NVmsRnd}}{{{rn['n_vms_used']}}}",
]

lines += ["", "% --- Section 5: winner share ---"]
tot = fs['n_bins'] + rn['n_bins']
all_share = {f: (fs['best_aic_share'][f]*fs['n_bins'] + rn['best_aic_share'][f]*rn['n_bins'])/tot
             for f in ["lognorm","weibull_min","gamma","norm"]}
lines += [
    f"\\newcommand{{\\FsLogNorm}}{{{100*fs['best_aic_share']['lognorm']:.2f}}}",
    f"\\newcommand{{\\FsWeibull}}{{{100*fs['best_aic_share']['weibull_min']:.2f}}}",
    f"\\newcommand{{\\FsGamma}}{{{100*fs['best_aic_share']['gamma']:.2f}}}",
    f"\\newcommand{{\\FsNormal}}{{{100*fs['best_aic_share']['norm']:.2f}}}",
    f"\\newcommand{{\\RndLogNorm}}{{{100*rn['best_aic_share']['lognorm']:.2f}}}",
    f"\\newcommand{{\\RndWeibull}}{{{100*rn['best_aic_share']['weibull_min']:.2f}}}",
    f"\\newcommand{{\\RndGamma}}{{{100*rn['best_aic_share']['gamma']:.2f}}}",
    f"\\newcommand{{\\RndNormal}}{{{100*rn['best_aic_share']['norm']:.2f}}}",
    f"\\newcommand{{\\LogNormShareAll}}{{{100*all_share['lognorm']:.2f}}}",
    f"\\newcommand{{\\WeibullShareAll}}{{{100*all_share['weibull_min']:.2f}}}",
    f"\\newcommand{{\\GammaShareAll}}{{{100*all_share['gamma']:.2f}}}",
    f"\\newcommand{{\\NormalShareAll}}{{{100*all_share['norm']:.2f}}}",
]

# Claim 1 CI from bootstrap
c1 = boot["claim1_winner_share"]
v = c1["combined_lognorm"]
lines += [
    f"\\newcommand{{\\LogNormShareAllCiLo}}{{{100*v['ci_low']:.2f}}}",
    f"\\newcommand{{\\LogNormShareAllCiHi}}{{{100*v['ci_hi']:.2f}}}",
]

# Pairwise AIC on combined
fs_df = pd.read_csv(os.path.join(HERE, "bitbrains_fit_results.csv"))
rn_df = pd.read_csv(os.path.join(HERE, "rnd_fit_results.csv"))
comb = pd.concat([fs_df, rn_df], ignore_index=True)
for fam, tag in [("norm","Norm"), ("gamma","Gamma"), ("weibull_min","Weibull")]:
    d = (comb["aic_lognorm"] - comb[f"aic_{fam}"]).replace([np.inf,-np.inf], np.nan).dropna()
    lines += [
        f"\\newcommand{{\\FsAicDelta{tag}}}{{{float(d.median()):.1f}}}",
        f"\\newcommand{{\\FsShareVs{tag}}}{{{100*float((d<0).mean()):.2f}}}",
        f"\\newcommand{{\\FsShareStrongVs{tag}}}{{{100*float((d<=-2).mean()):.2f}}}",
    ]

# A-D / CvM medians
lines += ["", "% --- Section 5 AD/CvM medians ---"]
for label, tag in [("fastStorage","Fs"),("rnd","Rn")]:
    a = adcvm[label]
    for stat, stag in [("ks","KS"),("cvm","Cvm"),("ad","Ad")]:
        med = a[f"{stat}_median"]
        lines += [
            f"\\newcommand{{\\{tag}{stag}MedLN}}{{{med['lognorm']:.2f}}}",
            f"\\newcommand{{\\{tag}{stag}MedNo}}{{{med['norm']:.2f}}}",
            f"\\newcommand{{\\{tag}{stag}MedGa}}{{{med['gamma']:.2f}}}",
            f"\\newcommand{{\\{tag}{stag}MedWe}}{{{med['weibull_min']:.2f}}}",
            f"\\newcommand{{\\{tag}{stag}ShareLN}}{{{100*a[f'{stat}_share_lognorm_best']:.1f}}}",
        ]

# --- Section 7 (mechanism) Claim 2 CIs ---
lines += ["", "% --- Section 7 (mechanism) ---"]
c2 = boot["claim2_scaling_mechanism"]
for label, tag in [("fastStorage","Fs"),("rnd","Rn")]:
    sp = c2[f"{label}_spearman"]; rt = c2[f"{label}_median_ratio"]
    lines += [
        f"\\newcommand{{\\Scal{tag}Spearman}}{{{sp['point']:.2f}}}",
        f"\\newcommand{{\\Scal{tag}SpearmanCiLo}}{{{sp['ci_low']:.2f}}}",
        f"\\newcommand{{\\Scal{tag}SpearmanCiHi}}{{{sp['ci_hi']:.2f}}}",
        f"\\newcommand{{\\Scal{tag}Ratio}}{{{rt['point']:.1f}}}",
        f"\\newcommand{{\\Scal{tag}RatioCiLo}}{{{rt['ci_low']:.1f}}}",
        f"\\newcommand{{\\Scal{tag}RatioCiHi}}{{{rt['ci_hi']:.1f}}}",
        f"\\newcommand{{\\Scal{tag}CohortN}}{{{c2[f'{label}_cohort_n']}}}",
    ]
for label, tag in [("fastStorage","Fs"),("rnd","Rn")]:
    s = sc[label]
    lines += [
        f"\\newcommand{{\\Scal{tag}NVms}}{{{s['n_vms']}}}",
        f"\\newcommand{{\\Scal{tag}MuMedR}}{{{s['mu_r2']['median']:.2f}}}",
        f"\\newcommand{{\\Scal{tag}MuShareHalf}}{{{100*s['mu_r2']['share_ge_0.5']:.1f}}}",
        f"\\newcommand{{\\Scal{tag}SigMedR}}{{{s['sigma_r2']['median']:.2f}}}",
        f"\\newcommand{{\\Scal{tag}SigShareHalf}}{{{100*s['sigma_r2']['share_ge_0.5']:.1f}}}",
        f"\\newcommand{{\\Scal{tag}AlphaMed}}{{{s['alpha_median']:.4f}}}",
        f"\\newcommand{{\\Scal{tag}GammaMed}}{{{s['gamma_median']:.3f}}}",
    ]

# --- Section 7 sizing: BOOTSTRAP POINT + CI from same source (fix mismatch bug) ---
lines += ["", "% --- Section 7 unified panel (bootstrap-derived point + CI) ---"]
c3 = boot["claim3_share_at_target"]
for label, tag, panel in [("fastStorage","Fs",un_fs),("rnd","Rn",un_rn)]:
    lines += [
        f"\\newcommand{{\\Panel{tag}NVms}}{{{panel['n_vms']}}}",
        f"\\newcommand{{\\Panel{tag}NBins}}{{{fmt_int(panel['n_bins'])}}}",
    ]
    for method, mtag in [("lognorm_ctop","LN"),("empirical_p998","EP"),
                         ("gauss_meanksd","GA"),("rolling_max","RM"),
                         ("ml_gbm_p998","MLGB"),("ewmq_p998","EWMQ")]:
        m = panel[method]
        share_boot = c3[label].get(method) if c3.get(label) else None
        # Ceiling and rel_cost come from the pooled panel (no CI in paper)
        lines += [
            f"\\newcommand{{\\U{tag}{mtag}MeanCov}}{{{100*m['mean_coverage']:.2f}}}",
            f"\\newcommand{{\\U{tag}{mtag}Ceiling}}{{{m['median_ceiling_pct']:.2f}}}",
            f"\\newcommand{{\\U{tag}{mtag}RelCost}}{{{100*m['median_rel_cost']:.1f}}}",
        ]
        # Share-at-target: use bootstrap point AND CI so they cannot conflict
        if share_boot is not None:
            lines += [
                f"\\newcommand{{\\U{tag}{mtag}Share}}{{{100*share_boot['point']:.2f}}}",
                f"\\newcommand{{\\U{tag}{mtag}ShareCiLo}}{{{100*share_boot['ci_low']:.2f}}}",
                f"\\newcommand{{\\U{tag}{mtag}ShareCiHi}}{{{100*share_boot['ci_hi']:.2f}}}",
            ]

# --- Section 8 SLA ---
lines += ["", "% --- Section 8 SLA net revenue (bootstrap) ---"]
c4 = boot["claim4_sla_net_revenue"]
for label, tag in [("fastStorage","Fs"),("rnd","Rn")]:
    if not c4.get(label): continue
    for prov in ["AWS","GCP","Azure"]:
        for method, mtag in [("lognorm_ctop","LN"),("empirical_p998","EP"),
                             ("gauss_meanksd","GA"),("rolling_max","RM"),
                             ("ml_gbm_p998","MLGB"),("ewmq_p998","EWMQ")]:
            v = c4[label][prov].get(method) if c4[label] and c4[label].get(prov) else None
            if v is None: continue
            lines += [
                f"\\newcommand{{\\Sla{tag}{mtag}{prov}Net}}{{{100*v['point']:.2f}}}",
                f"\\newcommand{{\\Sla{tag}{mtag}{prov}NetCiLo}}{{{100*v['ci_low']:.2f}}}",
                f"\\newcommand{{\\Sla{tag}{mtag}{prov}NetCiHi}}{{{100*v['ci_hi']:.2f}}}",
            ]

with open(PM, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

# --- Invariant check: verify point IN CI for every share-at-target macro ---
print("Invariant check (point in [CI_lo, CI_hi] for share_at_target):", file=sys.stderr)
bad = []
for label, tag in [("fastStorage","Fs"),("rnd","Rn")]:
    for method in ["lognorm_ctop","empirical_p998","gauss_meanksd","rolling_max","ml_gbm_p998","ewmq_p998"]:
        v = c3[label].get(method)
        if v is None: continue
        p, lo, hi = v['point'], v['ci_low'], v['ci_hi']
        ok = lo <= p <= hi
        if not ok: bad.append((label, method, p, lo, hi))
        print(f"  {tag} {method}: point={100*p:.2f} CI=[{100*lo:.2f}, {100*hi:.2f}] ok={ok}", file=sys.stderr)
print(f"BAD count: {len(bad)}", file=sys.stderr)

print(f"wrote {len(lines)} lines")
