"""Emit LaTeX macros for the direct-load (proxy-free) Section 5 result on
Alibaba, from direct_load_alibaba.json + direct_load_alibaba.csv. Container
count is the primary offered-load index (summed cpu_request saturates above
full provisioning). Names are letters-only (LaTeX rule).
"""
import json, os, collections
import pandas as pd, numpy as np
from scipy.stats import spearmanr
HERE = os.path.dirname(os.path.abspath(__file__))
d = json.load(open(os.path.join(HERE, "direct_load_alibaba.json")))
df = pd.read_csv(os.path.join(HERE, "direct_load_alibaba.csv"))

# decile Spearman on container count (the primary index)
df["dec"] = pd.qcut(df.ncont, 10, labels=False, duplicates="drop")
dec = df.groupby("dec").agg(ncont=("ncont", "median"), mu=("mu", "median"))
dec_rho = spearmanr(dec.ncont, dec.mu).statistic

# container-population facts (n distinct containers, n stops)
CMETA = r"E:/tmp/claude/E--Projects-Submitted-Amdocs/34878466-835f-474b-a49b-ee8b3bc3dbdb/scratchpad/alibaba/container_meta.csv"
conts = set(); nstop = 0
for line in open(CMETA):
    x = line.rstrip("\n").split(",")
    if len(x) < 8: continue
    conts.add(x[0])
    if x[4] == "stopped": nstop += 1

def L(n, v): return f"\\newcommand{{\\{n}}}{{{v}}}"
lines = ["% Auto-generated by scoping/build_direct_macros.py. Do not edit.",
         L("DirNMach", d["n_machines"]),
         L("DirNcontRho", f"{d['designB_mu_on_ncont']['spearman']:.2f}"),
         L("DirNcontDecRho", f"{dec_rho:.2f}"),
         L("DirSumreqRho", f"{d['designB_mu_on_lam']['spearman']:.2f}"),
         L("DirNegP", f"{d['negative_control']['between_machine_shuffled_abs_p95']:.2f}"),
         L("DirNcontainers", f"{len(conts):,}".replace(",", "\\,")),
         L("DirNstops", f"{nstop:,}".replace(",", "\\,"))]
with open(os.path.join(HERE, "..", "paper", "paper_macros_direct.tex"), "w") as f:
    f.write("\n".join(lines) + "\n")
print("\n".join(lines))
