"""Compute combined statistics across both public traces and write
paper/paper_macros.tex, plus regenerate the best_fit_share chart with both
datasets side by side."""
import json, os, sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
PAPER = os.path.normpath(os.path.join(HERE, "..", "paper"))
os.makedirs(PAPER, exist_ok=True)

fs = pd.read_csv(os.path.join(HERE, "bitbrains_fit_results.csv"))
rnd = pd.read_csv(os.path.join(HERE, "rnd_fit_results.csv"))
fs["dataset"] = "fastStorage"
rnd["dataset"] = "Rnd"
combined = pd.concat([fs, rnd], ignore_index=True)

CANDIDATES = ["lognorm", "norm", "gamma", "weibull_min"]
LABELS = {"lognorm": "Log-normal", "norm": "Normal", "gamma": "Gamma",
          "weibull_min": "Weibull"}

def winner_share(df):
    counts = df["best_aic"].value_counts()
    total = len(df)
    return {c: 100 * counts.get(c, 0) / total for c in CANDIDATES}

def pairwise(df, family):
    d = (df["aic_lognorm"] - df[f"aic_{family}"]).replace(
        [np.inf, -np.inf], np.nan).dropna()
    return {
        "median": float(d.median()),
        "share_lognorm_wins": 100 * float((d < 0).mean()),
        "share_strong": 100 * float((d <= -2).mean()),
    }

def bins_and_vms(df):
    return len(df), df["vm"].nunique()

fs_bins, fs_vms = bins_and_vms(fs)
rnd_bins, rnd_vms = bins_and_vms(rnd)
all_bins, all_vms = bins_and_vms(combined)

fs_share = winner_share(fs)
rnd_share = winner_share(rnd)
all_share = winner_share(combined)

def fmt_pct(x): return f"{x:.2f}"
def fmt_pct1(x): return f"{x:.1f}"
def fmt_int(n): return f"{n:,}".replace(",", "\\,")
def fmt_num(x): return f"{x:.1f}"

macros = []
def mac(name, val):
    macros.append(f"\\newcommand{{\\{name}}}{{{val}}}")

# dataset sizes
mac("RndVms", f"~{rnd_vms}")
mac("NVmsFs", fmt_int(fs_vms))
mac("NVmsRnd", fmt_int(rnd_vms))
mac("NVmsAll", fmt_int(all_vms))
mac("NBinsFs", fmt_int(fs_bins))
mac("NBinsRnd", fmt_int(rnd_bins))
mac("NBinsAll", fmt_int(all_bins))

# winner shares
for prefix, share in [("Fs", fs_share), ("Rnd", rnd_share)]:
    mac(f"{prefix}LogNorm", fmt_pct(share["lognorm"]))
    mac(f"{prefix}Weibull", fmt_pct(share["weibull_min"]))
    mac(f"{prefix}Gamma", fmt_pct(share["gamma"]))
    mac(f"{prefix}Normal", fmt_pct(share["norm"]))
mac("LogNormShareAll", fmt_pct(all_share["lognorm"]))
mac("WeibullShareAll", fmt_pct(all_share["weibull_min"]))
mac("GammaShareAll", fmt_pct(all_share["gamma"]))
mac("NormalShareAll", fmt_pct(all_share["norm"]))

# pairwise on the combined dataset (paper's headline pairwise)
for fam, tag in [("norm", "Norm"), ("gamma", "Gamma"),
                 ("weibull_min", "Weibull")]:
    p = pairwise(combined, fam)
    mac(f"FsAicDelta{tag}", fmt_num(p['median']))
    mac(f"FsShareVs{tag}", fmt_pct(p['share_lognorm_wins']))
    mac(f"FsShareStrongVs{tag}", fmt_pct(p['share_strong']))

with open(os.path.join(PAPER, "paper_macros.tex"), "w", encoding="utf-8") as f:
    f.write("% Auto-generated by scoping/build_paper_macros.py. Do not edit.\n")
    f.write("\n".join(macros) + "\n")

print(f"wrote {len(macros)} macros to paper/paper_macros.tex")

# --- Regenerate combined chart ---
fig, ax = plt.subplots(figsize=(7.2, 3.6))
order = ["lognorm", "weibull_min", "gamma", "norm"]
labels = [LABELS[o] for o in order]
fs_vals = [fs_share[o] for o in order]
rnd_vals = [rnd_share[o] for o in order]
y = np.arange(len(order))
h = 0.36
b1 = ax.barh(y - h/2, fs_vals, h, color="#3d65b8", label=f"fastStorage ({fs_bins:,} bins)")
b2 = ax.barh(y + h/2, rnd_vals, h, color="#c2542c", label=f"Rnd ({rnd_bins:,} bins)")
for b, v in zip(b1, fs_vals):
    ax.text(v + 0.9, b.get_y() + b.get_height()/2, f"{v:.1f}%", va="center", fontsize=9, color="#1e2126")
for b, v in zip(b2, rnd_vals):
    ax.text(v + 0.9, b.get_y() + b.get_height()/2, f"{v:.1f}%", va="center", fontsize=9, color="#1e2126")
ax.set_yticks(y); ax.set_yticklabels(labels)
ax.set_xlim(0, max(max(fs_vals), max(rnd_vals)) * 1.20)
ax.set_xlabel("share of hour-of-day bins (%)", fontsize=10, color="#545a63")
ax.invert_yaxis()
ax.spines["top"].set_visible(False); ax.spines["right"].set_visible(False); ax.spines["left"].set_visible(False)
ax.tick_params(axis="y", length=0); ax.tick_params(axis="x", colors="#545a63")
ax.grid(axis="x", color="#e6e6e3", linewidth=0.7); ax.set_axisbelow(True)
for sp in ax.spines.values(): sp.set_color("#dcdcda")
ax.legend(frameon=False, fontsize=9, loc="lower right")
fig.suptitle("Best-fitting family per hour-of-day bin, by AIC",
             fontsize=11, color="#1e2126", y=0.98)
plt.subplots_adjust(left=0.14, right=0.98, top=0.87, bottom=0.16)
plt.savefig(os.path.join(HERE, "best_fit_share.png"), dpi=180, facecolor="white")
plt.savefig(os.path.join(PAPER, "fig_best_fit_share.pdf"), facecolor="white")
print("chart written")
