"""Macros for the matched-coverage frontier (#1) and calibration (#2),
from frontier_calib_{alibaba,fastStorage}.json. Letters-only names.
"""
import json, os
import pandas as pd
HERE = os.path.dirname(os.path.abspath(__file__))
def L(n, v): return f"\\newcommand{{\\{n}}}{{{v}}}"
lines = ["% Auto-generated by scoping/build_frontier_calib_macros.py. Do not edit."]

def realized_at(cal, method, q):
    for r in cal[method]:
        if abs(r["nominal"] - q) < 1e-9:
            return r["realized_mean_cov"]
    return None

for label, pre in [("alibaba", "Ali"), ("fastStorage", "Fs")]:
    p = os.path.join(HERE, f"frontier_calib_{label}.json")
    if not os.path.exists(p): continue
    d = json.load(open(p))
    mc = d["matched_coverage"]
    lines += [L(f"Mc{pre}RmShare", f"{100*mc['rm_share_at_m1']:.1f}"),
              L(f"Mc{pre}LnK", f"{mc['ln_matched_K']:.1f}"),
              L(f"Mc{pre}LnShare", f"{100*mc['ln_matched_share']:.1f}"),
              L(f"Mc{pre}RmCeil", f"{mc['rm_median_ceiling_at_m1']:.2f}"),
              L(f"Mc{pre}LnCeil", f"{mc['ln_matched_median_ceiling']:.2f}"),
              L(f"Mc{pre}SavePct", f"{mc['ceiling_saving_pct']:.0f}")]
    cal = d["calibration"]
    lines += [L(f"Cal{pre}LnCov", f"{100*realized_at(cal,'lognorm',0.998):.1f}"),
              L(f"Cal{pre}GaCov", f"{100*realized_at(cal,'gauss',0.998):.1f}"),
              L(f"Cal{pre}EpCov", f"{100*realized_at(cal,'empirical',0.998):.1f}")]
    # Clear headline metric: capacity (median ceiling) to reach a target
    # realized coverage, per method, and log-normal's saving vs each.
    fr = pd.read_csv(os.path.join(HERE, f"frontier_{label}.csv"))
    def cap_at(method, tgt=0.98):
        dd = fr[fr.method == method].copy()
        i = (dd.mean_coverage - tgt).abs().idxmin()
        return float(dd.loc[i, "median_ceiling"])
    ln = cap_at("lognorm")
    lines += [L(f"Cap{pre}Ln", f"{ln:.2f}"),
              L(f"Cap{pre}Ga", f"{cap_at('gauss'):.2f}"),
              L(f"Cap{pre}Ep", f"{cap_at('empirical'):.2f}"),
              L(f"Cap{pre}Rm", f"{cap_at('rolling_max'):.2f}"),
              L(f"Cap{pre}SaveRm", f"{100*(1-ln/cap_at('rolling_max')):.0f}"),
              L(f"Cap{pre}SaveEp", f"{100*(1-ln/cap_at('empirical')):.0f}")]

with open(os.path.join(HERE, "..", "paper", "paper_macros_frontcal.tex"), "w") as f:
    f.write("\n".join(lines) + "\n")
print("\n".join(lines))
