"""Macro-ize the Section 6 mechanism-diagnostic numbers from the committed
rc_vm_summary.csv so a rebuild regenerates them. Letters-only names.
"""
import os
import pandas as pd, numpy as np
HERE = os.path.dirname(os.path.abspath(__file__))
d = pd.read_csv(os.path.join(HERE, "rc_vm_summary.csv"))
def L(n, v): return f"\\newcommand{{\\{n}}}{{{v}}}"
comp_rise = min((d.rho_lam_sb > 0).mean(), (d.rho_lam_sw > 0).mean())
lines = ["% Auto-generated by scoping/build_diag_macros.py. Do not edit.",
         L("DiagProxyRho", f"{d.rho_cpu_net.median():.2f}"),
         L("DiagBimodal", f"{100*d.bimodal_share.median():.0f}"),
         L("DiagSkewHi", f"{d.med_skew_hi.median():.1f}"),
         L("DiagMaxPNine", f"{d.max_p95.median():.0f}"),
         L("DiagCompRise", f"{100*comp_rise:.0f}"),
         L("DiagFracBetween", f"{d.med_frac_between.median():.2f}")]
with open(os.path.join(HERE, "..", "paper", "paper_macros_diag.tex"), "w") as f:
    f.write("\n".join(lines) + "\n")
print("\n".join(lines))
