"""Calibrated SLA variant (reviewer B7). The headline SLA table treats every
CPU sample above the ceiling as unavailable time, which places per-VM
availability around 0.96-0.98 and the resulting net revenue deep in the
penalty regime (79-87%). To show the method ranking is not an artefact of
that regime, we recalibrate: scale the unavailability by a constant s per
trace so the grand-median method availability lands at a realistic 0.999,
i.e. A' = 1 - s*(1 - A), then re-apply the SLA schedules. The recalibration
is a single monotone transform applied identically to every method, so it
changes the operating regime without hand-tuning any method.
Reads unified_{fastStorage,rnd,alibaba}.csv.
"""
import json, os
import numpy as np, pandas as pd
HERE = os.path.dirname(os.path.abspath(__file__))
METHODS = ["lognorm_ctop", "empirical_p998", "gauss_meanksd", "rolling_max"]
TARGET_MED = 0.999

def credit(a, prov):
    if a >= 0.9999: return 0.0
    if a >= 0.99:   return 0.10
    if a >= 0.95:   return 0.25
    return 1.00 if prov != "GCP" else 0.50

def per_vm_avail(df, m):
    col = f"cov_{m}"
    def wm(g):
        ok = g[col].notna()
        return (g.loc[ok, col]*g.loc[ok, "n_test"]).sum()/g.loc[ok, "n_test"].sum() if ok.any() else np.nan
    return df.groupby("vm").apply(wm, include_groups=False).dropna()

out = {}
for label in ["fastStorage", "rnd", "alibaba"]:
    fp = os.path.join(HERE, f"unified_{label}.csv")
    if not os.path.exists(fp): continue
    df = pd.read_csv(fp)
    avail = {m: per_vm_avail(df, m) for m in METHODS}
    grand_med = float(np.median(np.concatenate([a.values for a in avail.values()])))
    s = (1 - TARGET_MED) / (1 - grand_med)   # maps grand median -> 0.999
    res = {"raw_grand_median_availability": grand_med, "downtime_scale_s": s}
    for prov in ["AWS", "GCP"]:
        pm = {}
        for m in METHODS:
            Acal = 1 - s * (1 - avail[m])
            net = Acal.apply(lambda a: 1 - credit(a, prov))
            pm[m] = {"cal_availability_median": float(Acal.median()),
                     "net_revenue_ratio": float(net.mean())}
        res[prov] = pm
    out[label] = res

with open(os.path.join(HERE, "calibrated_sla.json"), "w") as f:
    json.dump(out, f, indent=2)

# print + rank check
for label, r in out.items():
    print(f"[{label}] raw grand-median avail={r['raw_grand_median_availability']:.4f} s={r['downtime_scale_s']:.3f}")
    for prov in ["AWS"]:
        row = {m: r[prov][m]["net_revenue_ratio"] for m in METHODS}
        best = max(row, key=row.get)
        print(f"   {prov} calibrated net revenue: " +
              " ".join(f"{m.split('_')[0]}={100*row[m]:.2f}" for m in METHODS) +
              f"   -> winner: {best}")

# macros (fastStorage AWS calibrated)
def L(n, v): return f"\\newcommand{{\\{n}}}{{{v}}}"
lines = ["% Auto-generated by scoping/calibrated_sla.py. Do not edit."]
if "fastStorage" in out:
    fs = out["fastStorage"]["AWS"]
    lines += [L("CalSlaLn", f"{100*fs['lognorm_ctop']['net_revenue_ratio']:.1f}"),
              L("CalSlaRm", f"{100*fs['rolling_max']['net_revenue_ratio']:.1f}"),
              L("CalSlaEp", f"{100*fs['empirical_p998']['net_revenue_ratio']:.1f}"),
              L("CalSlaGa", f"{100*fs['gauss_meanksd']['net_revenue_ratio']:.1f}")]
with open(os.path.join(HERE, "..", "paper", "paper_macros_calsla.tex"), "w") as f:
    f.write("\n".join(lines) + "\n")
print("\n".join(lines))
