"""Multiple-comparison correction over the family of paired sign tests that
certify the log-normal revenue lead. GCP/Azure share the AWS win/loss counts
(the sign test depends only on which method is cheaper per VM, not the credit
magnitude), so the unique family is the AWS tests across the three traces:
fastStorage (5 baselines) + Rnd (5) + Alibaba (4) = 14 tests. Applies
Holm-Bonferroni (FWER) and Benjamini-Hochberg (FDR) at 0.05.
"""
import json, os
import numpy as np
HERE = os.path.dirname(os.path.abspath(__file__))

fam = []  # (label, p)
sp = json.load(open(os.path.join(HERE, "sla_paired_summary.json")))
for trace in ["fastStorage", "rnd"]:
    for base, o in sp[trace]["AWS"].items():
        fam.append((f"{trace}:{base}", o["sign_test_p_two_sided"]))
ali = json.load(open(os.path.join(HERE, "alibaba_panel_stats.json")))
for base, o in ali["paired_vs_lognorm_AWS"].items():
    fam.append((f"alibaba:{base}", o["sign_test_p"]))

labels = [f[0] for f in fam]
p = np.array([f[1] for f in fam])
m = len(p)
order = np.argsort(p)

# Holm-Bonferroni
holm_sig = np.zeros(m, bool)
for rank, idx in enumerate(order):
    if p[idx] <= 0.05 / (m - rank):
        holm_sig[idx] = True
    else:
        break

# Benjamini-Hochberg
bh_sig = np.zeros(m, bool)
psorted = p[order]
thresh = 0.05 * (np.arange(1, m + 1)) / m
below = psorted <= thresh
if below.any():
    kmax = np.max(np.where(below))
    bh_sig[order[:kmax + 1]] = True

print(f"family size m = {m}")
print(f"{'test':32s} {'p':>10s} {'Holm':>6s} {'BH':>6s}")
for i in np.argsort(p):
    print(f"{labels[i]:32s} {p[i]:10.2e} {str(bool(holm_sig[i])):>6s} {str(bool(bh_sig[i])):>6s}")

n_holm = int(holm_sig.sum()); n_bh = int(bh_sig.sum())
# which fail Holm
fail_holm = [labels[i] for i in range(m) if not holm_sig[i]]
out = {"family_size": m, "n_significant_holm": n_holm, "n_significant_bh": n_bh,
       "fail_holm": fail_holm,
       "min_p": float(p.min()), "max_p": float(p.max())}
with open(os.path.join(HERE, "mc_correction.json"), "w") as f:
    json.dump(out, f, indent=2)
print("\n", json.dumps(out, indent=2))

# macro
lines = ["% Auto-generated by scoping/mc_correction.py. Do not edit.",
         f"\\newcommand{{\\McFamily}}{{{m}}}",
         f"\\newcommand{{\\McHolmN}}{{{n_holm}}}",
         f"\\newcommand{{\\McBHN}}{{{n_bh}}}"]
with open(os.path.join(HERE, "..", "paper", "paper_macros_mc.tex"), "w") as f:
    f.write("\n".join(lines) + "\n")
